const DEFAULT_TOKENS = [
  'Ai66LHZG9MCzg1WKdawwqduVAX',
  '9cRCn9rGT8V2imeM2BaKs13yhMEais3ruM3rPvTGpump',
  'DuVgdHeEk7ejWPxWY5G3PQA99oEGGLmnbWuWWxpEpump',
  'FCaPNUJbWfECeeCeA3tvqkGUQ1BFPuon71KphJM5pump'
];
const CFG={buyWatch:4,highRisk:-3,minTx:8,priceSpike:5,priceDump:10,volVelocity:2,liqAdd:10,liqDrop:20,lowLiq:10000};
let previous=JSON.parse(localStorage.getItem('snapshots')||'{}');
let tokens=JSON.parse(localStorage.getItem('tokens')||'null')||DEFAULT_TOKENS;
let timer=null;
const $=s=>document.querySelector(s);
const money=n=>{n=Number(n||0);if(!n)return '$0';if(n>=1e9)return '$'+(n/1e9).toFixed(2)+'B';if(n>=1e6)return '$'+(n/1e6).toFixed(2)+'M';if(n>=1e3)return '$'+(n/1e3).toFixed(1)+'K';return '$'+n.toFixed(2)};
const price=n=>{n=Number(n||0);if(!n)return '$0';if(n<.000001)return '$'+n.toExponential(3);if(n<.01)return '$'+n.toFixed(8);return '$'+n.toFixed(4)};
function pickPairs(raw){const out={};for(const p of raw||[]){if(p.chainId!=='solana')continue;for(const t of tokens){if(p.baseToken?.address===t||p.quoteToken?.address===t){if(!out[t]||Number(p.liquidity?.usd||0)>Number(out[t].liquidity?.usd||0))out[t]=p}}}return out}
function score(t,p){const tx=p.txns?.m5||{},v=p.volume||{},c=p.priceChange||{},liq=Number(p.liquidity?.usd||0),buys=Number(tx.buys||0),sells=Number(tx.sells||0),v5=Number(v.m5||0),v1=Number(v.h1||0),pc5=Number(c.m5||0);let s=0,r=[];const total=buys+sells;if(total>=CFG.minTx&&buys>=Math.max(3,sells*1.5)){s+=2;r.push(`Buy pressure ${buys}B/${sells}S`)}if(pc5>=CFG.priceSpike){s+=2;r.push(`Price +${pc5.toFixed(1)}% in 5m`)}const avg=v1/12;if(avg>0&&v5>=avg*CFG.volVelocity){s+=2;r.push(`Volume velocity ${(v5/avg).toFixed(1)}x`)}if(pc5<=-CFG.priceDump){s-=3;r.push(`Price ${pc5.toFixed(1)}% in 5m`)}if(total>=CFG.minTx&&sells>=Math.max(3,buys*2)){s-=2;r.push(`Sell pressure ${buys}B/${sells}S`)}const old=previous[t]?.liq||0;if(old>0){const ch=(liq-old)/old*100;if(ch>=CFG.liqAdd){s+=1;r.push(`Liquidity +${ch.toFixed(1)}%`)}if(ch<=-CFG.liqDrop){s-=5;r.push(`LIQUIDITY DROP ${ch.toFixed(1)}%`)}}if(liq&&liq<CFG.lowLiq){s-=1;r.push(`Low liquidity ${money(liq)}`)}return{score:s,status:s>=CFG.buyWatch?'BUY WATCH':s<=CFG.highRisk?'HIGH RISK':'NEUTRAL',reasons:r.length?r:['No strong trigger'],liq}}
async function refresh(){if(!tokens.length){renderEditor();$('#tokenList').innerHTML='<div class="status">Add a Solana token to start.</div>';return}$('#status').textContent='Checking live market data…';$('#refreshBtn').disabled=true;try{const url='https://api.dexscreener.com/tokens/v1/solana/'+tokens.slice(0,30).join(',');const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Market-data request failed');const pairs=pickPairs(await res.json());let buy=0,risk=0;$('#tokenList').innerHTML='';for(const t of tokens){const p=pairs[t];if(!p){renderMissing(t);continue}const sc=score(t,p);if(sc.status==='BUY WATCH')buy++;if(sc.status==='HIGH RISK')risk++;renderCard(t,p,sc);maybeNotify(t,p,sc);previous[t]={liq:sc.liq,status:sc.status}}localStorage.setItem('snapshots',JSON.stringify(previous));$('#buyCount').textContent=buy;$('#riskCount').textContent=risk;$('#updatedAt').textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('#status').textContent='Live scan complete.'}catch(e){$('#status').textContent='Could not load live data. Check internet access or API availability.';console.error(e)}finally{$('#refreshBtn').disabled=false}}
function renderCard(t,p,sc){const node=$('#tokenCardTemplate').content.cloneNode(true),card=node.querySelector('.token-card'),badge=node.querySelector('.badge');node.querySelector('.symbol').textContent=p.baseToken?.symbol||t.slice(0,6);node.querySelector('.name').textContent=p.baseToken?.name||t;badge.textContent=sc.status;badge.classList.add(sc.status==='BUY WATCH'?'buy':sc.status==='HIGH RISK'?'risk':'neutral');node.querySelector('.price').textContent=price(p.priceUsd);const ch=Number(p.priceChange?.m5||0),ce=node.querySelector('.change');ce.textContent=(ch>=0?'+':'')+ch.toFixed(1)+'% / 5m';ce.classList.add(ch>=0?'up':'down');node.querySelector('.mcap').textContent=money(p.marketCap||p.fdv);node.querySelector('.liq').textContent=money(p.liquidity?.usd);node.querySelector('.buys').textContent=p.txns?.m5?.buys??0;node.querySelector('.sells').textContent=p.txns?.m5?.sells??0;node.querySelector('.vol').textContent=money(p.volume?.m5);node.querySelector('.score').textContent=(sc.score>0?'+':'')+sc.score;node.querySelector('.reasons').textContent=sc.reasons.join(' • ');const a=node.querySelector('.dex-link');a.href=p.url||'#';$('#tokenList').appendChild(card)}
function renderMissing(t){const d=document.createElement('article');d.className='token-card';d.innerHTML=`<div class="card-top"><div><h3 class="symbol">${t.slice(0,8)}…</h3><div class="name">No active DEX pair found</div></div><span class="badge">NO DATA</span></div>`;$('#tokenList').appendChild(d)}
function maybeNotify(t,p,sc){const prior=previous[t]?.status;if(prior&&prior!==sc.status&&(sc.status==='BUY WATCH'||sc.status==='HIGH RISK')&&Notification.permission==='granted'){new Notification(`${p.baseToken?.symbol||'Token'}: ${sc.status}`,{body:sc.reasons.join(' • '),icon:'icons/icon-192.png'})}}
function renderEditor(){const el=$('#watchlistEditor');el.innerHTML='';tokens.forEach((t,i)=>{const row=document.createElement('div');row.className='watch-row';row.innerHTML=`<code>${t}</code><button data-i="${i}">Remove</button>`;row.querySelector('button').onclick=()=>{tokens.splice(i,1);saveTokens()};el.appendChild(row)})}
function saveTokens(){localStorage.setItem('tokens',JSON.stringify(tokens));renderEditor();refresh()}
$('#addBtn').onclick=()=>{const v=$('#tokenInput').value.trim();if(v&& !tokens.includes(v)){tokens.push(v);$('#tokenInput').value='';saveTokens()}};
$('#refreshBtn').onclick=refresh;
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return alert('Notifications are not available in this browser.');const p=await Notification.requestPermission();$('#notifyBtn').textContent=p==='granted'?'Alerts enabled':'Alerts blocked'};
$('#autoRefresh').onchange=e=>{clearInterval(timer);if(e.target.checked)timer=setInterval(refresh,60000)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderEditor();refresh();timer=setInterval(refresh,60000);
